title: macOS Mastered
description: The ultimate guide to macOS for developers and power users. From beginner settings to expert terminal commands.
theme: jekyll-theme-cayman
lang: en-US

show_downloads: true
google_analytics:

plugins:
  - jekyll-seo-tag
